export const robots = [
  {
    id: 0,
    username: "one",
    name: "Mr One",
    email: "One@gmail.com",
  },
  {
    id: 1,
    username: "jemie",
    name: "jay jay",
    email: "jemieofoegbu@gmail.com",
  },
  {
    id: 2,
    username: "pope",
    name: "popzilla",
    email: "popzilla@gmail.com",
  },
  {
    id: 3,
    username: "chinko",
    name: "pachinko",
    email: "pachinko@gmail.com",
  },
  {
    id: 4,
    username: "cha cha",
    name: "chan chan",
    email: "chanchan@gmail.com",
  },
  {
    id: 5,
    username: "kaka",
    name: "kaka smith",
    email: "kaka@gmail.com",
  },
  {
    id: 6,
    username: "guzman",
    name: "guzman",
    email: "el'chappo@gmail.com",
  },
  {
    id: 7,
    username: "nardo",
    name: "Nardo ",
    email: "zaramu@gmail.com",
  },
  {
    id: 8,
    username: "Toby",
    name: "Toby Jason",
    email: "tobby@gmail.com",
  },
  {
    id: 9,
    username: "zero",
    name: "Mr Zero",
    email: "Zero@gmail.com",
  },
  {
    username: "user10",
    name: "John Smith",
    email: "john.smith10@example.com",
    id: 10,
  },
  {
    username: "user11",
    name: "Jane Doe",
    email: "jane.doe11@example.com",
    id: 11,
  },
  {
    username: "user12",
    name: "Bob Johnson",
    email: "bob.johnson12@example.com",
    id: 12,
  },
  {
    username: "user13",
    name: "Samantha Williams",
    email: "samantha.williams13@example.com",
    id: 13,
  },
  {
    username: "user14",
    name: "Michael Brown",
    email: "michael.brown14@example.com",
    id: 14,
  },
  {
    username: "user15",
    name: "Emily Davis",
    email: "emily.davis15@example.com",
    id: 15,
  },
  {
    username: "user16",
    name: "Jacob Miller",
    email: "jacob.miller16@example.com",
    id: 16,
  },
  {
    username: "user17",
    name: "Nicholas Garcia",
    email: "nicholas.garcia17@example.com",
    id: 17,
  },
  {
    username: "user18",
    name: "Amanda Rodriguez",
    email: "amanda.rodriguez18@example.com",
    id: 18,
  },
  {
    username: "user19",
    name: "Christopher Martinez",
    email: "christopher.martinez19@example.com",
    id: 19,
  },
  {
    username: "user20",
    name: "Ashley Taylor",
    email: "ashley.taylor20@example.com",
    id: 20,
  },
];
